# Generated by Django 2.0.5 on 2020-12-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_property_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_proof1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sellerid', models.CharField(max_length=300)),
                ('aadhar_card', models.CharField(max_length=300)),
                ('pan_card', models.BigIntegerField()),
                ('voter_id', models.CharField(max_length=200)),
                ('driving_licence', models.CharField(max_length=300)),
            ],
        ),
    ]
