# Generated by Django 2.0.5 on 2020-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_upload_proof1'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unid2', models.CharField(max_length=300)),
                ('uploadid1', models.CharField(max_length=300)),
                ('seller_name', models.CharField(max_length=300)),
                ('member_count', models.CharField(max_length=300)),
                ('member1', models.BigIntegerField()),
                ('member2', models.CharField(max_length=200)),
                ('member1_phone', models.CharField(max_length=300)),
                ('member2_phone', models.CharField(max_length=300)),
                ('relation_name', models.CharField(max_length=300)),
                ('relation_phone', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='upload_proof1',
            name='unid1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
