# Generated by Django 2.0.5 on 2020-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20201201_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_details',
            name='member1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property_upload',
            name='property_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload_proof1',
            name='pan_card',
            field=models.CharField(max_length=300),
        ),
    ]
