# Generated by Django 2.0.5 on 2020-12-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20201203_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='family_details',
            new_name='family_details1',
        ),
    ]
