# Generated by Django 2.0.5 on 2020-12-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20201203_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_details1',
            name='sellerid',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
