# Generated by Django 2.0.5 on 2020-11-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyer_register',
            new_name='buyer_reg',
        ),
    ]
