# Generated by Django 2.0.5 on 2020-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20201120_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sellerid', models.CharField(max_length=300)),
                ('sellername', models.CharField(max_length=200)),
                ('buyerid', models.CharField(max_length=200)),
                ('buyername', models.CharField(max_length=300)),
                ('pro_id', models.CharField(max_length=200)),
                ('pr_size', models.CharField(max_length=200)),
                ('pr_price', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=200)),
                ('validity', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=200)),
                ('holder_name', models.CharField(max_length=200)),
            ],
        ),
    ]
