# Generated by Django 2.0.5 on 2020-12-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payment1',
        ),
    ]
